### ISSUE TITLE
#vagrant_location script execution encoding output issue.

### ISSUE THREAD

**Issue by fables-tales** [org-binbab/gem-vagrant-wrapper#12]
Hi!

I'm working on encoding issues on vagrant. Specifically, we encountered this issue: https://github.com/mitchellh/vagrant/issues/6056 filed against us.

I've created a patch branch for it here: https://github.com/samphippen/gem-vagrant-wrapper/tree/samphippen/bugfix/mitchellh/vagrant/6056

This is the critical commit that fixes the issue: https://github.com/samphippen/gem-vagrant-wrapper/commit/53f8f1674c14e15c980a2de4c116a3ae9b4c6a35

I can't create a PR for this branch, because master is not based off this version of the gem. Is there any forward porting that needs to happen here?

**Comment by mitchellh** [comment]
Looks great!

**Comment by babelop** [comment]
@samphippen and @mitchellh I'm genuinely keen to help, but I feel that something may be lost in the communication. You've said you cannot create a pull request because your branch it out-of-date, but to the best of my knowledge we've successfully addressed the binary issue with the latest version of the gem, and in a way which bypasses encoding issues. Can you please clarify what it is you are trying to improve, and why your changes cannot (should not) be based off the active master?

**Comment by fables-tales** [comment]
Hi @binarybabel so I'd believe you've fixed this in your 2.x release series, but we have someone who's filed a bug against vargant in the 1.x series. It's up to you to decide whether you'd like to continue to support that series, but given that there's an open bug against vagrant for this version, we'd appreciate it if you could create a 1.x release with this patch.

If not, that's fine, and we'll close the issue against vagrant itself and advise the reporter to upgrade. Let me  know :)

**Comment by babelop** [comment]
@samphippen Although the 2.x series is the only one that includes this patch, that series itself was not a breaking change against 1.x, but rather an indicator of the added support for Windows. The 2.x series is essentially backwards compatible with any linux version of vagrant. So I only see upgrading being a problem if there is some type of packaging complication whereby some crucial and stale package is ~ linked to the 1.x series.

By all means please let me know if there is an intractable problem being created by this decision; it's not my desire to leave anyone out to dry, but I honestly see no reason why the upgrade shouldn't be made given it is just a gemspec or gemfile change. It seems like a waste of resources to maintain 1.x given that circumstance.

Best,
