### ISSUE TITLE
vagrant-wrapper breaks the command line

### ISSUE THREAD

**Issue by Annih** [org-binbab/gem-vagrant-wrapper#7]
Hello,

Due to the way `vagrant-wrapper` is passing its arguments to vagrant it is breaking the original command line.
For example `vagrant winrm -c 'sh "C:\Program Files\MyBin.exe"'` will call vagrant with the following ARGV:
```ruby
["winrm", "-c", "sh", "C:\Program Files\MyBin.exe"]
```

Obviously that's not what you want :)

Edit: [here is the fix](https://github.com/org-binbab/gem-vagrant-wrapper/pull/8)

**Comment by tknerr** [comment]
Some more test cases to be verified: 

 * `vagrant ssh -c "echo foo"`
 * `vagrant up --provider=virtualbox`
